kind: pipeline
name: kobo-dotfile-hack

steps:
- name: build-native
  image: gcc:latest
  commands:
  - cd ./kobo-dotfile-hack
  - mkdir -p ./tmp/.kobo ./tmp/.test ./tmp/.adobe-digital-editions ./tmp/.adds
  - HOME=./tmp make -f Makefile.native test
  depends_on: [clone]
- name: build-kobo
  image: geek1011/kobo-toolchain:latest
  commands:
  - cd ./kobo-dotfile-hack
  - apt -qq update >/dev/null && apt -qq install -y make >/dev/null
  - make CROSS_PREFIX=arm-nickel-linux-gnueabihf-
  depends_on: [clone]
- name: upload
  image: debian:9
  commands:
  - cd ./kobo-dotfile-hack
  - apt -qq update >/dev/null && apt -qq install -y curl >/dev/null
  - curl -F'file=@KoboRoot.tgz' https://0x0.st
  depends_on: [build-kobo]
