CC      ?= $(CROSS_TC)-gcc
STRIP   ?= $(CROSS_TC)-strip
CONFIG  := -DLS_ONLY

override CFLAGS := $(CONFIG) -Wall -Wextra -shared -std=gnu99 -fPIC $(CFLAGS)
LIBS := -ldl

.PHONY: all clean test

all: libhidedir_native.so

clean:
	rm -f libhidedir_native.so

test: all
	@echo "=== WITHOUT ==="
	ls -lah $(HOME)
	@echo "=== WITH ==="
	LD_PRELOAD="$(PWD)/libhidedir_native.so" ls -lah $(HOME)

libhidedir_native.so: hidedir.c
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)
	$(STRIP) --strip-unneeded $@
